[package]
name = "fog-ocall-oram-storage-untrusted"
version = "1.1.1"
authors = ["MobileCoin"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
mc-common = { path = "../../../mobilecoin/common", features = ["log"] }
lazy_static = "1.4"
