[package]
name = "fog-uri"
version = "1.1.2-pre0"
authors = ["MobileCoin"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
mc-util-uri = { path = "../../mobilecoin/util/uri" }

[dev-dependencies]
mc-common = { path = "../../mobilecoin/common" }
