[package]
name = "generate_test_foundation_key"
version = "1.0.1-pre1"
authors = ["MobileCoin"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
rand = "0.7"
mc-account-keys = { path = "../mobilecoin/account-keys" }
